name: Deploy to GitHub Packages

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and Deploy
        run: mvn clean deploy
        env:
          GITHUB_ACTOR : 'matheusverissimo'
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
